//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 12:54:13 PM EET 
//


package com.dfotiou.api.soap.geolocation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dfotiou.api.soap.geolocation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dfotiou.api.soap.geolocation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNearestPointRequest }
     * 
     */
    public GetNearestPointRequest createGetNearestPointRequest() {
        return new GetNearestPointRequest();
    }

    /**
     * Create an instance of {@link GetNearestPointResponse }
     * 
     */
    public GetNearestPointResponse createGetNearestPointResponse() {
        return new GetNearestPointResponse();
    }

    /**
     * Create an instance of {@link GetFrequentPointsRequest }
     * 
     */
    public GetFrequentPointsRequest createGetFrequentPointsRequest() {
        return new GetFrequentPointsRequest();
    }

    /**
     * Create an instance of {@link GetFrequentPointsResponse }
     * 
     */
    public GetFrequentPointsResponse createGetFrequentPointsResponse() {
        return new GetFrequentPointsResponse();
    }

}
