//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 12:54:13 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dfotiou.com/api/soap/geolocation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dfotiou.api.soap.geolocation;
